version: '3.7'
services:
  service1:
    container_name: service1
    build: ./service1
    image: python-service1:latest
    ports:
    - target: 5000
      published: 5000
  service4:
    container_name: service4
    build: ./service4
    image: python-service4:latest
    ports:
    - target: 6000
      published: 6000
  service2:
    container_name: service2
    build: ./service2
    image: python-service2:latest
    ports:
    - target: 5001
      published: 5001
  service3:
    container_name: service3
    build: ./service3
    image: python-service3:latest
    ports:
    - target: 5002
      published: 5002
