services:
  db:
    container_name: db
    image: db:latest
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ppword
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      timeout: 20s
#      retries: 10
  service1:
    container_name: service1
    build: ./service1
    image: python-service1:latest
#    depends_on:
#      database:
#        condition: service_healthy
    environment:
      DATABASE_PASSWORD: ppword
    ports:
    - target: 5000
      published: 5000
  service4:
    container_name: service4
    build: ./service4
    image: python-service4:latest
    ports:
    - target: 6000
      published: 6000
  service2:
    container_name: service2
    build: ./service2
    image: python-service2:latest
    ports:
    - target: 5001
      published: 5001
  service3:
    container_name: service3
    build: ./service3
    image: python-service3:latest
    ports:
    - target: 5002
      published: 5002
