version: '3.8'
services:
  db:
    container_name: db
    image: fabriziodea/db:1
    build: ./db
    deploy:
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: ppword
    volumes:
    - type: volume
      source: myvolume
      target: /var/lib/db
  service1:
    container_name: service1
    build: ./service1
    image: fabriziodea/service1:D
    deploy:
      replicas: 3
#    depends_on:
#      db:
#        condition: service_healthy
    environment:
      DATABASE_PASSWORD: ppword
    ports:
    - target: 5000
      published: 5000  
  service2:
    container_name: service2
    build: ./service2
    image: fabriziodea/service2:1
    deploy:
      replicas: 2
    ports:
    - target: 5001
      published: 5001
  service3:
    container_name: service3
    build: ./service3
    image: fabriziodea/service3:1
    deploy:
      replicas: 2
    ports:
    - target: 5002
      published: 5002
  service4:
    container_name: service4
    build: ./service4
    image: fabriziodea/service4:1
    deploy:
      replicas: 2
    ports:
    - target: 6000
      published: 6000
volumes:
  myvolume:
