- name: Install Docker Dependancies
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3
    - python3-pip
    - python-setuptools
    state: latest
    update_cache: yes
  tags: docker

- name: Install docker
  shell:
    cmd: curl https://get.docker.com | bash

- name: add user to docker group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes

- name: "Install with pip"
  pip:
    name:
      - docker-py
      - jsondiff
      - requests
      - pyyaml
    executable: pip3
