all:
  children:
    managers:
      hosts:
        swarmanager:
    workers:
      hosts:
        swarmworker:
    nginx:
      hosts:
        nginx:

  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'